[build]
command = ""
publish = "."

[build.environment]
NODE_VERSION = "18"

# Configuración específica para evitar el modo SPA
[site]
bucket = "."

# Configuración de rutas para preservar archivos estáticos
[[redirects]]
from = "/propiedades/en-venta.html"
to = "/propiedades/en-venta.html"
status = 200

[[redirects]]
from = "/propiedades/en-arriendo.html"
to = "/propiedades/en-arriendo.html"
status = 200

[[redirects]]
from = "/propiedades/oportunidades.html"
to = "/propiedades/oportunidades.html"
status = 200

# Configuración para propiedades dinámicas (solo cuando hay parámetros)
[[redirects]]
from = "/propiedades/*"
to = "/propiedad-dinamica.html"
status = 200
condition = "query_string contains 'slug'"

# Configuración para archivos estáticos
[[redirects]]
from = "/*.html"
to = "/:splat.html"
status = 200

# Configuración para assets
[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/components/*"
to = "/components/:splat"
status = 200 